import os
import sqlite3
import psycopg

SQLITE_DB = os.path.join("data", "clinic_database.db")
DATABASE_URL = os.environ.get("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set.")

TABLES = {
    "doctors": [
        "id", "name", "base_salary", "telegram_bot_token",
        "telegram_chat_id", "telegram_enabled", "username",
        "password_hash", "birth_year", "email", "role",
        "reset_token_hash", "reset_token_expires_at", "created_at"
    ],
    "patients": [
        "id", "greg_date", "eth_date", "patient_name", "ticket_no",
        "procedure", "total_fee", "doctor_pct", "my_earning",
        "doctor_id", "created_at"
    ],
    "settings": [
        "key", "value"
    ],
    "audit_log": [
        "id", "doctor_id", "doctor_name", "action", "entity",
        "entity_id", "detail", "created_at"
    ],
    "telegram_outbox": [
        "id", "doctor_id", "message_text", "attempts", "last_error",
        "created_at", "sent_at"
    ],
}


def create_schema(conn):
    with conn.cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS doctors (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL UNIQUE,
                base_salary DOUBLE PRECISION DEFAULT 45000.0,
                telegram_bot_token TEXT DEFAULT '',
                telegram_chat_id TEXT DEFAULT '',
                telegram_enabled BOOLEAN DEFAULT FALSE,
                username TEXT DEFAULT '',
                password_hash TEXT DEFAULT '',
                birth_year INTEGER DEFAULT 0,
                email TEXT DEFAULT '',
                role TEXT DEFAULT 'doctor',
                reset_token_hash TEXT DEFAULT '',
                reset_token_expires_at TEXT DEFAULT '',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS patients (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                greg_date TEXT,
                eth_date TEXT,
                patient_name TEXT,
                ticket_no TEXT,
                procedure TEXT,
                total_fee DOUBLE PRECISION,
                doctor_pct DOUBLE PRECISION,
                my_earning DOUBLE PRECISION,
                doctor_id BIGINT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS settings (
                key TEXT PRIMARY KEY,
                value TEXT
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS audit_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                doctor_id BIGINT,
                doctor_name TEXT,
                action TEXT,
                entity TEXT,
                entity_id TEXT,
                detail TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS telegram_outbox (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                doctor_id BIGINT,
                message_text TEXT NOT NULL,
                attempts INTEGER DEFAULT 0,
                last_error TEXT DEFAULT '',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                sent_at TIMESTAMP
            )
        """)

    conn.commit()


def migrate_table(pg_conn, sqlite_conn, table, columns):
    placeholders = ", ".join(["%s"] * len(columns))
    column_sql = ", ".join(f'"{c}"' for c in columns)

    rows = sqlite_conn.execute(
        f'SELECT {column_sql} FROM "{table}"'
    ).fetchall()

    with pg_conn.cursor() as cur:
        for row in rows:
            values = list(row)

            if table == "doctors":
                # SQLite uses 0/1; PostgreSQL uses boolean.
                values[5] = bool(values[5])

            cur.execute(
                f"""
                INSERT INTO "{table}" ({column_sql})
                VALUES ({placeholders})
                ON CONFLICT DO NOTHING
                """,
                values,
            )

    pg_conn.commit()
    return len(rows)


def reset_sequences(pg_conn):
    with pg_conn.cursor() as cur:
        for table in ("doctors", "patients", "audit_log", "telegram_outbox"):
            cur.execute(
                f"""
                SELECT setval(
                    pg_get_serial_sequence('{table}', 'id'),
                    COALESCE((SELECT MAX(id) FROM "{table}"), 1),
                    (SELECT COUNT(*) > 0 FROM "{table}")
                )
                """
            )
    pg_conn.commit()


def count_rows(conn, table):
    with conn.cursor() as cur:
        cur.execute(f'SELECT COUNT(*) FROM "{table}"')
        return cur.fetchone()[0]


def main():
    if not os.path.isfile(SQLITE_DB):
        raise FileNotFoundError(
            f"SQLite database not found: {SQLITE_DB}"
        )

    print("Opening SQLite database...")
    sqlite_conn = sqlite3.connect(SQLITE_DB)

    print("Connecting to PostgreSQL...")
    pg_conn = psycopg.connect(DATABASE_URL)

    try:
        print("Creating PostgreSQL schema...")
        create_schema(pg_conn)

        print("Migrating data...")

        for table, columns in TABLES.items():
            count = migrate_table(
                pg_conn,
                sqlite_conn,
                table,
                columns,
            )
            print(f"  {table}: {count} SQLite row(s) processed")

        reset_sequences(pg_conn)

        print("\nVerification:")
        for table in TABLES:
            sqlite_count = sqlite_conn.execute(
                f'SELECT COUNT(*) FROM "{table}"'
            ).fetchone()[0]

            postgres_count = count_rows(
                pg_conn,
                table,
            )

            status = "OK" if sqlite_count == postgres_count else "MISMATCH"

            print(
                f"  {table}: "
                f"SQLite={sqlite_count}, "
                f"PostgreSQL={postgres_count} "
                f"[{status}]"
            )

        print("\nMigration completed.")

    finally:
        sqlite_conn.close()
        pg_conn.close()


if __name__ == "__main__":
    main()